### ISSUE TITLE
Colors are outdated

### ISSUE THREAD

**Issue by privatenumber** [windicss/docs#161]
The new colors from v34 are not in the docs: https://windicss.org/posts/v34.html

- slate
- zinc
- neutral
- stone

Also, seems `gray-900` is not `18181b` as the current docs say as it was replaced by `zinc-900`

**Comment by hannoeru** [comment]
Updated, if it didn't update, refresh the web page or cleanup service worker and try again.

**Comment by privatenumber** [comment]
Thanks @hannoeru !
