### ISSUE TITLE
typo in rollup docs: array destructuring

### ISSUE THREAD

**Issue by milahu** [windicss/docs#191]
https://github.com/windicss/docs/blob/892c3ce5f720c91458a3b16a17bc15572f1f6341/integrations/rollup.md?plain=1#L17-L25

should be `WindiCSS()`

**Comment by milahu** [comment]
confusing confusing ...

https://github.com/windicss/vite-plugin-windicss/issues/265 says it must be `...WindiCSS()`

**Comment by hannoeru** [comment]
This is supported by rollup after v3.1.0
https://github.com/rollup/rollup/pull/4657
