### ISSUE TITLE
Windicss doesn't auto extend configuration options like said in docs

### ISSUE THREAD

**Issue by danbulant** [windicss/docs#35]
[configuration#no-need-to-clear-defaults](https://windicss.org/guide/configuration.html#no-need-to-clear-defaults) says that any configuration option will extend options, but that seems to not be the case in windicss. I still need to use the `extend` option, else the options will get overridden.

(Issue created from discord discussion, [message link](https://discordapp.com/channels/810981250981953597/819462973029351425/825326518405693470) in #svelte)

**Comment by hannoeru** [comment]
Only extends will extends default theme config, and the config under theme will overwrite default theme config.

**Comment by antfu** [comment]
Agreed with should remove that statement. It's always better to let users aware they are extending the config.
