### ISSUE TITLE
Broken links in docs

### ISSUE THREAD

**Issue by jordienr** [windicss/docs#40]
There are some broken links in https://windicss.org/guide/vite.html#installation-%F0%9F%92%BF

- In Configuration the link to options.ts is broken.

- Link to ./example.html also doesn't seem to work.

- Link to Vitesse@feat/windicss also doesn't seem to work.

I'd submit a PR, but I'm not sure what the correct links are. 

Thanks for making windicss and have a good day :)

**Comment by antfu** [comment]
We are working on a new docs site, and sorry for the misalignment.
