### ISSUE TITLE
vue-windicss-preprocess has been archived by the owner.

### ISSUE THREAD

**Issue by multics** [windicss/docs#41]
As the owner mentioned [here](https://github.com/windicss/vue-windicss-preprocess#readme).
> This package will be archived, we will give up support for it, please switch your project to [windicss-webpack-plugin](https://github.com/windicss/windicss-webpack-plugin).

So the [guide](https://windicss.org/guide/vue.html) might to update to catch up the decision.

**Comment by antfu** [comment]
We are actively working on a new docs site which will be live soon
https://next.windicss.org/guide/installation.html
