### ISSUE TITLE
[Docs] Maybe a confuse in Windi 3.0?

### ISSUE THREAD

**Issue by harrytran998** [windicss/docs#56]
I read here and I confuse the alias which is required or not? Hope you guy can modify it 😁!
![image](https://user-images.githubusercontent.com/24296018/116808512-659f9000-ab63-11eb-9376-78a68fd81f61.png)

**Comment by hannoeru** [comment]
fixed in https://github.com/windicss/docs/commit/e3d684fc4ba9de3c1e1a1b4e757bd9a4d6c14dc4
