### ISSUE TITLE
Anchor tag overflows container element on smaller screens 

### ISSUE THREAD

**Issue by levandovsky** [windicss/docs#88]
Found it in /posts/v31
![image](https://user-images.githubusercontent.com/44808257/120892256-09bea000-c616-11eb-8ec6-d94fd2380fe0.png)

p.s.

I can't seem to find `@windicss/vitepress-theme` repo to fix this 😅

**Comment by hannoeru** [comment]
The theme repo is inside https://github.com/windicss/doc-utils.

fixed in https://github.com/windicss/doc-utils/commit/5293bbd33ec95ec7f8d623a1cd75979a5f9b4be7
